/** Seed content matching the provided JD Gold design layouts. */
export const PAGE_SEEDS = [
  {
    slug: 'about',
    title: 'About JD Gold',
    content: {
      layout: 'about',
      brandTagline: 'Building Trust In Gold',
      logoSrc: '/images/jd-gold-logo.png',
      heroImage: '/images/product-investment-grade-bar.png',
      heroImageAlt: 'JD GOLD Fine Gold 999.9 1000g bar',
      heroBackgroundImage: '/images/product-cast-gold-bars.png',
      aboutHeading: 'ABOUT JD GOLD',
      aboutBody:
        'JD GOLD is a name of trust, excellence and quality in the gold industry. With decades of experience, a commitment to purity, and customer satisfaction, we continue to set new benchmarks in the world of gold trading, refining, and jewelry.',
      aboutBodySecondary:
        'We believe in honesty, transparency, and building lasting relationships with our clients worldwide.',
      pillars: [
        {
          title: 'TRUSTED LEGACY',
          description:
            'Built on decades of trust, integrity, and excellence in the gold industry.',
          icon: 'shield',
        },
        {
          title: 'PREMIUM QUALITY',
          description:
            'We deal in 99.9% pure gold, ensuring the highest international standards.',
          icon: 'diamond',
        },
        {
          title: 'INTEGRITY & TRANSPARENCY',
          description:
            'Our business is built on honesty, transparency, and ethical gold practices.',
          icon: 'handshake',
        },
        {
          title: 'GLOBAL PRESENCE',
          description:
            'Proudly serving clients across the globe with dedication and professionalism.',
          icon: 'globe',
        },
      ],
      leadershipHeading: 'OUR LEADERSHIP',
      leaders: [
        {
          title: 'DIRECTOR & FOUNDER',
          name: 'Syed Abid Hussain Bukhari',
          experience: '45 Years Experience in Gold Industry',
          image: '/images/management-lead-1.png',
          imageAlt: 'Syed Abid Hussain Bukhari',
        },
        {
          title: 'CHAIRMAN & FOUNDER',
          name: 'Syed Amir Abid Bukhari',
          experience: '15 Years Experience in Gold Industry',
          image: '/images/management-lead-2-new.png',
          imageAlt: 'Syed Amir Abid Bukhari',
        },
        {
          title: 'CEO & CO-FOUNDER',
          name: "Ma'am Dilara Amir Bukhari",
          experience: '10 Years Experience in Gold Industry',
          image: '/images/management-lead-dilara-new.png',
          imageAlt: "Ma'am Dilara Amir Bukhari",
        },
      ],
      jewelleryDeptHeading: 'JD GOLD JEWELLERY DEPARTMENT',
      jewelleryDeptManagedBy: "Managed By Ma'am Dilara Amir Bukhari",
      jewelleryDeptBody:
        "Our Jewellery Department is managed by Ma'am Dilara Amir Bukhari, ensuring creativity, quality, and customer satisfaction in every piece we create.",
      jewelleryDeptImages: [
        {
          src: '/images/management-lead-dilara-new.png',
          alt: 'Jewellery department showroom',
        },
        {
          src: '/images/hero-slide-whatsapp-05.png',
          alt: 'Gold necklace collection',
        },
      ],
      collectionHeading: 'OUR JEWELLERY COLLECTION',
      collectionImages: [
        { src: '/images/hero-slide-whatsapp-04.png', alt: 'Gold bangles' },
        { src: '/images/hero-slide-whatsapp-05.png', alt: 'Bridal necklace set' },
        { src: '/images/hero-slide-whatsapp-06.png', alt: 'Gold jewellery close-up' },
        { src: '/images/hero-slide-whatsapp-07.png', alt: 'Ornate gold necklace' },
        { src: '/images/hero-slide-whatsapp-08.png', alt: 'Gold rings and coins' },
      ],
      commitmentHeading: 'OUR COMMITMENT',
      commitmentBody:
        'At JD GOLD, we are committed to delivering excellence in every gram of gold and every piece of jewellery. Your trust is our greatest asset.',
      commitments: [
        {
          title: 'BEST QUALITY',
          description: 'Guaranteed purity and authenticity.',
          icon: 'badge',
        },
        {
          title: 'FAIR PRICING',
          description: 'Transparent rates and fair deals.',
          icon: 'scale',
        },
        {
          title: 'SAFE & SECURE',
          description: 'Secure transactions and data protection.',
          icon: 'lock',
        },
        {
          title: 'CUSTOMER SATISFACTION',
          description: 'Your satisfaction is our top priority.',
          icon: 'people',
        },
      ],
      contact: {
        phone: '+92 300 1234567',
        email: 'info@jdgold.com',
        website: 'www.jdgold.com',
        address: 'Suite # 01, Gold Tower, Main Boulevard, Karachi, Pakistan',
      },
      footerImage: '/images/product-cast-gold-bars.png',
    },
  },
  {
    slug: 'license-and-offices',
    title: 'License & Offices',
    content: {
      layout: 'licenses',
      logoSrc: '/images/jd-gold-logo.png',
      heading: 'JD GOLD LICENSE & OFFICES',
      subtitle: 'GLOBAL LICENSES. WORLDWIDE OFFICES. TRUSTED EVERYWHERE.',
      heroImage: '/images/product-investment-grade-bar.png',
      heroImageAlt: 'JD GOLD Fine Gold 999.9 bar',
      offices: [
        {
          number: 1,
          country: 'CHINA',
          flagSrc: '/images/flags/china.svg',
          details: [
            { label: 'LICENSE TYPE', value: 'Certificate of Incorporation' },
            { label: 'LICENSE / CERTIFICATE', value: 'Companies Registry Certificate' },
            { label: 'REGISTERED COMPANY', value: 'Golden Ants Group Company Limited' },
            { label: 'REGISTRATION NUMBER', value: '2581935' },
            { label: 'ISSUE DATE', value: '20 September 2017' },
          ],
          officeLocation: 'Beijing, China (Head Office)',
          licenseImage: '/images/license-hong-kong-incorporation.png',
          licenseImageAlt: 'China certificate of incorporation',
          officeImage: '/images/location-dubai-refinery.png',
          officeImageAlt: 'China office building',
        },
        {
          number: 2,
          country: 'DUBAI',
          flagSrc: '/images/flags/dubai.svg',
          details: [
            { label: 'LICENSE TYPE', value: 'Commercial License' },
            { label: 'LICENSE / CERTIFICATE', value: 'Dubai Economy & Tourism' },
            { label: 'LICENSE NUMBER', value: '1183376' },
            { label: 'ISSUE DATE', value: '08/05/2023' },
            { label: 'EXPIRY DATE', value: '07/05/2024' },
          ],
          officeLocation: 'Dubai, United Arab Emirates (Office)',
          licenseImage: '/images/license-dubai-ded-commercial-license.png',
          licenseImageAlt: 'Dubai commercial license',
          officeImage: '/images/management-gallery-11.png',
          officeImageAlt: 'Dubai office interior',
        },
        {
          number: 3,
          country: 'QATAR',
          flagSrc: '/images/flags/qatar.svg',
          details: [
            { label: 'LICENSE TYPE', value: 'Commercial Registration' },
            { label: 'LICENSE / CERTIFICATE', value: 'Ministry of Commerce & Industry' },
            { label: 'COMMERCIAL REG. NO.', value: '1' },
            { label: 'ISSUE DATE', value: '20/07/2018' },
            { label: 'EXPIRY DATE', value: '19/07/2028' },
          ],
          officeLocation: 'Doha, Qatar (Office)',
          licenseImage: '/images/license-qatar-commercial-registration.png',
          licenseImageAlt: 'Qatar commercial registration',
          officeImage: '/images/management-gallery-12.png',
          officeImageAlt: 'Qatar office',
        },
        {
          number: 4,
          country: 'PAKISTAN',
          flagSrc: '/images/flags/pakistan.svg',
          details: [
            { label: 'LICENSE TYPE', value: 'Certificate of Incorporation' },
            { label: 'LICENSE / CERTIFICATE', value: 'Securities & Exchange Commission of Pakistan' },
            { label: 'INCORPORATION DATE', value: '04 June 2021' },
            { label: 'COMPANY TYPE', value: 'Private Limited Company' },
          ],
          officeLocation: 'Karachi, Pakistan (Office)',
          licenseImage: '/images/license-pakistan-secp-incorporation.png',
          licenseImageAlt: 'Pakistan SECP incorporation',
          officeImage: '/images/about-refinery-portrait.png',
          officeImageAlt: 'Pakistan office',
        },
        {
          number: 5,
          country: 'USA',
          flagSrc: '/images/flags/usa.svg',
          details: [
            { label: 'LICENSE TYPE', value: 'Certificate of Trading Licence' },
            { label: 'LICENSE / CERTIFICATE', value: 'Financial Service Commission' },
            { label: 'COMPANY NUMBER', value: '14597' },
            { label: 'ISSUE DATE', value: '20 February 2014' },
            { label: 'COMPANY TYPE', value: 'Gold Bullions, Nuggets, Jewelry Imports & Export Services' },
          ],
          officeLocation: 'New York, USA (Office)',
          licenseImage: '/images/license-usa-jd-gold-trading.png',
          licenseImageAlt: 'USA trading licence',
          officeImage: '/images/management-collage-01.png',
          officeImageAlt: 'USA office',
        },
        {
          number: 6,
          country: 'UGANDA',
          flagSrc: '/images/flags/uganda.svg',
          details: [
            { label: 'LICENSE TYPE', value: 'Certificate of Incorporation' },
            { label: 'LICENSE / CERTIFICATE', value: 'Ministry of Commerce' },
            { label: 'INCORPORATION DATE', value: '04 June 2021' },
            { label: 'COMPANY TYPE', value: 'Private Limited Company' },
          ],
          officeLocation: 'Kampala, Uganda (Office)',
          licenseImage: '/images/license-uganda-certificate-of-incorporation.png',
          licenseImageAlt: 'Uganda certificate of incorporation',
          officeImage: '/images/management-collage-02.png',
          officeImageAlt: 'Uganda office',
        },
      ],
      footerPoints: [
        {
          title: 'Legally Licensed',
          description: 'All licenses are valid and issued by respective government authorities.',
          icon: 'shield',
        },
        {
          title: 'Global Presence',
          description: 'Strategic offices in key markets around the world.',
          icon: 'globe',
        },
        {
          title: 'Trust & Transparency',
          description: 'Committed to legal compliance and ethical business practices.',
          icon: 'handshake',
        },
        {
          title: 'Excellence',
          description: 'Delivering quality, value and excellence worldwide.',
          icon: 'trophy',
        },
      ],
    },
  },
  {
    slug: 'factories-and-refinery',
    title: 'Market, Advantages & Achievements',
    content: {
      layout: 'advantages',
      logoSrc: '/images/jd-gold-logo.png',
      heading: 'JD GOLD MARKET, ADVANTAGES & ACHIEVEMENTS',
      subtitle: 'A LEADER IN PURITY. A LEGACY OF TRUST.',
      heroImage: '/images/product-cast-gold-bars.png',
      heroImageAlt: 'JD GOLD Fine Gold bar and coins',
      blocks: [
        {
          number: '1',
          title: 'QUALITY',
          subtitle: 'OUR PROMISE OF PURITY',
          image: '/images/hero-slide-gold-bar-hand.png',
          imageAlt: 'JD Gold bar quality inspection',
          points: [
            'We source only the finest raw materials from trusted and verified suppliers.',
            'All our gold is 100% pure with 999.9 finest quality.',
            'International quality standards and strict quality control at every stage.',
            'Advanced assaying and testing to ensure perfection.',
            'Commitment to delivering unmatched quality and lasting value.',
          ],
          sideItems: [
            { title: '100% PURE GOLD 999.9' },
            { title: 'INTERNATIONAL QUALITY STANDARDS' },
            { title: 'STRICT QUALITY CONTROL' },
            { title: 'TRUSTED & VERIFIED SUPPLY CHAIN' },
          ],
        },
        {
          number: '2',
          title: 'PRICING',
          subtitle: 'TRANSPARENT. FAIR. COMPETITIVE.',
          image: '/images/product-cast-gold-bars.png',
          imageAlt: 'JD Gold bars — fair market pricing',
          points: [
            'Competitive pricing in the global gold market.',
            'Transparent and clear pricing with no hidden charges.',
            'Best value for money with assured purity.',
            'Long-term relationships built on trust and fairness.',
            'Flexible solutions tailored to client needs.',
          ],
          sideItems: [
            { title: 'MARKET-ALIGNED RATES' },
            { title: 'NO HIDDEN CHARGES' },
            { title: 'FLEXIBLE SOLUTIONS' },
            { title: 'TRANSPARENT TRADE' },
          ],
        },
        {
          number: '3',
          title: 'TECHNOLOGY',
          subtitle: 'INNOVATION THAT DELIVERS EXCELLENCE.',
          image: '/images/hero-slide-whatsapp-08.png',
          imageAlt: 'Modern refining technology',
          imageFirst: true,
          points: [
            'State-of-the-art refining and manufacturing technology.',
            'Advanced testing, assaying and quality verification systems.',
            'Secure digital systems for transparency and traceability.',
            'Continuous investment in innovation and modern infrastructure.',
            'Technology-driven operations for excellence and growth.',
          ],
          sideItems: [
            { title: 'ADVANCED MACHINERY' },
            { title: 'PRECISION ASSAYING' },
            { title: 'DIGITAL SECURITY' },
            { title: 'INNOVATION ALWAYS' },
          ],
        },
        {
          number: '4',
          title: 'EXPERIENCE',
          subtitle: 'YEARS OF TRUST. WORLDWIDE IMPACT.',
          image: '/images/hero-slide-company-wealth.png',
          imageAlt: 'Global shipping and trade',
          points: [
            'Years of experience have made us a name of trust in the global gold industry.',
            'Decades of expertise in gold trading, refining and distribution.',
            'Deep understanding of global markets and client needs.',
            'Skilled professionals and dedicated team.',
            'Strong global network and industry reputation.',
          ],
          sideItems: [
            { title: 'DECADES OF EXPERIENCE' },
            { title: 'GLOBAL MARKET EXPERTISE' },
            { title: 'THOUSANDS OF SATISFIED CLIENTS' },
            { title: 'TRUSTED BY LEADERS WORLDWIDE' },
          ],
        },
        {
          number: '5',
          title: 'SPEED OR RELIABILITY',
          subtitle: 'ON TIME. EVERY TIME.',
          image: '/images/product-gold-weighed.png',
          imageAlt: 'On-time delivery and reliability',
          imageFirst: true,
          points: [
            'We deliver on time, every time — with speed and reliability.',
            'Timely delivery and quick turnaround.',
            'Reliable logistics and secure transportation.',
            '24/7 operational support and client assistance.',
            'Consistent performance and commitment.',
            'Your trust is our responsibility.',
          ],
          sideItems: [
            { title: 'ON TIME DELIVERY' },
            { title: 'SECURE & RELIABLE LOGISTICS' },
            { title: '24/7 SUPPORT' },
            { title: 'TRUSTED WORLDWIDE' },
          ],
        },
      ],
      achievementsHeading:
        'OUR ACHIEVEMENTS ARE A REFLECTION OF OUR HARD WORK, DEDICATION AND CLIENT TRUST.',
      achievements: [
        {
          title: 'AWARDS',
          points: [
            'Recognized for excellence in quality and purity.',
            'Awarded for best customer service and business ethics.',
            'ISO certified for quality management.',
          ],
          image: '/images/management-gallery-award.png',
          imageAlt: 'Awards',
        },
        {
          title: 'MAJOR CLIENTS',
          points: [
            'Serving banks, jewellers, investors and institutions worldwide.',
            'Long-term partnerships built on trust.',
            'Global client base continues to grow.',
          ],
          image: '/images/management-collage-03.png',
          imageAlt: 'Major clients',
        },
        {
          title: 'COMPLETED PROJECTS',
          points: [
            'Successfully completed large-scale gold supply projects.',
            'Supplying gold to multiple industries and markets.',
            'Track record of excellence in every project.',
          ],
          image: '/images/product-cast-gold-bars.png',
          imageAlt: 'Completed projects',
        },
        {
          title: 'GLOBAL PRESENCE',
          points: [
            'Offices in China, Dubai, Qatar, Pakistan, USA and Uganda.',
            'Strong global network and presence.',
            'Expanding for a brighter and golden future.',
          ],
          image: '/images/location-dubai-refinery.png',
          imageAlt: 'Global presence',
        },
      ],
      footerMottos: [
        { title: 'PURITY', subtitle: 'YOU CAN TRUST', icon: 'shield' },
        { title: 'VALUE', subtitle: 'YOU DESERVE', icon: 'bars' },
        { title: 'PARTNERSHIP', subtitle: 'YOU CAN RELY ON', icon: 'handshake' },
        { title: 'EXCELLENCE', subtitle: 'WE DELIVER', icon: 'star' },
      ],
      footerLogoTagline: 'A SYMBOL OF TRUST, QUALITY & EXCELLENCE.',
      closingLine: 'JD GOLD – POWERED BY TRUST, DRIVEN BY EXCELLENCE.',
    },
  },

];
